# Generated by Django 2.2.6 on 2019-12-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
